// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shop.Data;

#nullable disable

namespace Shop.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Shop.Shared.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ActionTo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBuy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<string>("Shop")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Apple",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 2,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Banana",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 3,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Orange",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 4,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Milk",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 5,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Bread",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 6,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Butter",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 7,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Cheese",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 8,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Yogurt",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 9,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Chicken",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        },
                        new
                        {
                            Id = 10,
                            ActionTo = new DateTime(2026, 2, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            IsBuy = false,
                            Name = "Rice",
                            Price = 28.899999999999999,
                            Shop = "Lidl"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
